apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: db
spec:
  containers:
    - name: postgres
      image: postgres:15-alpine
      ports:
        - name: postgres
          containerPort: 5432
      envFrom:
        - secretRef:
           name: db-secrets
