apiVersion: v1
kind: Pod
metadata:
  name: pg-inspect
spec:
  containers:
    - name: inspector
      image: postgres:15-alpine
      command: ["sleep", "3600"]
      volumeMounts:
      - mountPath: /var/lib/postgresql
        name: pgdata
  volumes:
    - name: pgdata
      persistentVolumeClaim:
        claimName: db-pvc
